services:
  db:
    image: orchardup/postgresql
    ports: 
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker"]
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - /var/lib/postgresql
  web:
    build: ./
    links:
      - db
    depends_on:
      db:
        condition: service_healthy 
    ports:
      - 9090:5000